- name: Installs dovecot & passlib
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - dovecot-imapd
    - python-passlib

- name: Fixes some default files
  template:
    src: "{{ item }}.j2"
    dest: /etc/dovecot/conf.d/{{ item }}
  notify: Restart dovecot
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf

- name: Creates default_login_user group
  group:
    name: "{{ dovecot_default_login_user.group }}"
    gid: "{{ dovecot_default_login_user.gid | default(omit) }}"
  when: dovecot_default_login_user

- name: Creates default_login_user user
  user:
    name: "{{ dovecot_default_login_user.user }}"
    group: "{{ dovecot_default_login_user.group }}"
    uid: "{{ dovecot_default_login_user.uid | default(omit) }}"
  when: dovecot_default_login_user

- name: Adds local.conf
  template:
    src: local.conf.j2
    dest: /etc/dovecot/local.conf
  notify: Restart dovecot


- name: Creates master users hashes
  htpasswd:
#  command: doveadm pw -s sha1 -u {{ item.key }} -p {{ item.value }}
    path: /etc/dovecot/passwd.master
    name: "{{ item.key }}"
    password: "{{ item.value }}"
    crypt_scheme: ldap_sha1
  with_dict: "{{ dovecot_master_users }}"
